#!/bin/sh
export COMMON=--builddir=dist/aarch64-apple-darwin14
export COMPILE="--with-ghc=aarch64-apple-darwin14-ghc
                --with-ghc-pkg=aarch64-apple-darwin14-ghc-pkg
                --with-gcc=aarch64-apple-darwin14-clang
                --with-ld=aarch64-apple-darwin14-ld
                --hsc2hs-options=--cross-compile"
export CONFIG="--configure-option=--host=aarch64-apple-darwin14 --disable-shared"

# Some extra options, depending on what command was invoked.
case $1 in
    configure|install) OPTIONS="$COMMON $COMPILE $CONFIG" ;;
    build)             OPTIONS="$COMMON $COMPILE" ;;
    list|info|update)  OPTIONS="" ;;
    "")                OPTIONS="" ;;
    *)                 OPTIONS="$COMMON" ;;
esac

# FIXME: Hard coded
exec $HOME/ghc-ios/host-sysroot/bin/cabal \
  --config-file=$HOME/ghc-ios/host-sysroot/.cabal/config \
  $OPTIONS "$@"

