#!/bin/sh

TARGET_PLATFORM=`xcrun --show-sdk-platform-path --sdk iphonesimulator`
TARGET_BIN=`xcrun --show-sdk-platform-path --sdk iphonesimulator`/Developer/usr/bin
TARGET_LDFLAGS="-sysrootlib $TARGET_PLATFORM -arch i386"

exec $TARGET_LD $TARGET_LDFLAGS "$@"