#!/bin/sh
if [ "$IOS_I386_BUILD_SYSROOT" = ""  ]; then
  echo "Environment variable IOS_I386_BUILD_SYSROOT is not set"
  exit 1
fi

export COMMON="--builddir=dist/i386-apple-darwin11"
export COMPILE="--with-ghc=i386-apple-darwin11-ghc
                --with-ghc-pkg=i386-apple-darwin11-ghc-pkg
                --with-gcc=i386-apple-darwin11-clang
                --with-ld=i386-apple-darwin11-ld
                --hsc2hs-options=--cross-compile"

export CONFIG="--configure-option=--host=i386-apple-darwin11
               --prefix=$IOS_I386_BUILD_SYSROOT
               --disable-shared
               --extra-include-dirs=$IOS_I386_BUILD_SYSROOT/include
               --extra-lib-dirs=$IOS_I386_BUILD_SYSROOT/lib
               --disable-library-profiling"

exec "`dirname $0`/common-cross-cabal" "$@"
